// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Flux.TranstemLab.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("TestingCD34SelectionCD34Selection")]
    public partial class TestingCD34SelectionCD34SelectionFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "TestingCD34SelectionCD34Selection.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "TestingCD34SelectionCD34Selection", "\tIn order to ensure methods and steps are working properly while saving time\r\n\tAs" +
                    " an SQA intern\r\n\tI want to run a test with steps only for CD34 Selection - Data " +
                    "Analysis CD34 Selection", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Data Analysis CD34 Selection")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        [NUnit.Framework.TestCaseAttribute("290", "3.07", "0.68", "14.3", "99.0", "272", "2.95", "0.82", "17.5", "98.8", "A0", "82", "5.53", "90.57", "0.04", "99.2", "421", "1.72", "0.11", "19.2", "94.0", null)]
        public virtual void DataAnalysisCD34Selection(
                    string hPCBeforePrepTotalVolume, 
                    string hPCBeforePrepNucleatedCellCount, 
                    string hPCBeforePrepPercentCD34Positve, 
                    string hPCBeforePrepPercentCD3Positive, 
                    string hPCBeforePrepCD34Viability, 
                    string hPCAfterPrepTotalVolume, 
                    string hPCAfterPrepNucleatedCellCount, 
                    string hPCAfterPrepPercentCD34Positve, 
                    string hPCAfterPrepPercentCD3Positive, 
                    string hPCAfterPrepCD34Viability, 
                    string cD34PositiveFractionAliquotID, 
                    string cD34PositiveFractionTotalVolume, 
                    string cD34PositiveFractionNucleatedCellCount, 
                    string cD34PositiveFractionPercentCD34Positve, 
                    string cD34PositiveFractionPercentCD3Positive, 
                    string cD34PositiveFractionCD34Viability, 
                    string cD34NegativeFractionTotalVolume, 
                    string cD34NegativeFractionNucleatedCellCount, 
                    string cD34NegativeFractionPercentCD34Positve, 
                    string cD34NegativeFractionPercentCD3Positive, 
                    string cD34NegativeFractionCD34Viability, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "mytag"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Data Analysis CD34 Selection", @__tags);
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
    testRunner.Given("I navigate to TranstemLab application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
    testRunner.Then("I click on Product Link and select Batch Processing to Search page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 10
    testRunner.And("I click on Add Batch button to Add Batch page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
    testRunner.Then("I change the Date Range", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
    testRunner.And("I select Cell Processing v1 20111 from the drop down list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
    testRunner.And("I click on Search button in the Add Batch page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
    testRunner.Then("I select the first product in the table", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 15
 testRunner.And("I click on the Set Batch button to navigate to Processing Procedure page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
    testRunner.Then("I select a Technologist from Technologist Name drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 17
    testRunner.And("I click on Save button to save the Processing Procedure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
    testRunner.Then("I click on Product List and navigate to Processing page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 19
 testRunner.Then("I click on the Title Arrow", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 20
 testRunner.Then("I navigate to Data Analysis CD34 Selection", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 21
 testRunner.And(string.Format("I fill in HPC Product Aliquot for CD34 Selection (Before Prep/Magnetic Labeling) " +
                        "with {0}, {1}, {2}, {3}, {4}", hPCBeforePrepTotalVolume, hPCBeforePrepNucleatedCellCount, hPCBeforePrepPercentCD34Positve, hPCBeforePrepPercentCD3Positive, hPCBeforePrepCD34Viability), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.And(string.Format("I fill in HPC Product Aliquot for CD34 Selection (After Prep/Magnetic Labeling) w" +
                        "ith {0}, {1}, {2}, {3}, {4}", hPCAfterPrepTotalVolume, hPCAfterPrepNucleatedCellCount, hPCAfterPrepPercentCD34Positve, hPCAfterPrepPercentCD3Positive, hPCAfterPrepCD34Viability), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.And(string.Format("I fill in CD34 Selected Positive Fraction (Cell Collection Bag) with {0}, {1}, {2" +
                        "}, {3}, {4}, {5}", cD34PositiveFractionAliquotID, cD34PositiveFractionTotalVolume, cD34PositiveFractionNucleatedCellCount, cD34PositiveFractionPercentCD34Positve, cD34PositiveFractionPercentCD3Positive, cD34PositiveFractionCD34Viability), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.And(string.Format("I fill in CD34 Selected Negative Fraction (Negative Fraction Bag) with {0}, {1}, " +
                        "{2}, {3}, {4}", cD34NegativeFractionTotalVolume, cD34NegativeFractionNucleatedCellCount, cD34NegativeFractionPercentCD34Positve, cD34NegativeFractionPercentCD3Positive, cD34NegativeFractionCD34Viability), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.And("I verify the calculations in Data Analysis CD34 Selection", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
