// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Flux.TranstemLab.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Test Calc")]
    public partial class TestCalcFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "TestingCD34SelectionAll.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Test Calc", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test Calc")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        [NUnit.Framework.TestCaseAttribute("Test", "TF", "TL", "MR", "CR", "RID", "", "452", "5.02", "5", "22.6", "0", "22.69", "90.4", "542.4", "3.99", "21.64", "4", "21.7", "522", "4.37", "22.8", "2", "10.4", "166", "13.76", "22.84", "7", "11.6", "95.4", "105.4", "100.2", "419", "40", "4.88", "0.19", "10.9", "2/6/15", "09:15", "1", "327", "37", "0", "290", "340", "552", "123", "15", "838", "0", "325", "225", "6150106017", "6150106017", "11:13", "1", "0", "1337", "11:43", "353", "123", "15", "838", "465", "462", "456", "15", "838", "457", "115", "0", "1", "309", "6/2/15", "15:19", "6/2/15", "16:04", "2304", "104", "22.0", "M60F0004S4002N1", "1", "", "", "", "", "", "1", "", "", "", "", "", "1", "", "", "", "", "1", "", "", "", "", "", "", "", "", "", "", "", "290", "3.07", "0.68", "14.3", "99.0", "272", "2.95", "0.82", "17.5", "98.8", "A0", "82", "5.53", "90.57", "0.04", "99.2", "421", "1.72", "0.11", "19.2", "94.0", null)]
        public virtual void TestCalc(
                    string recipientID, 
                    string firstName, 
                    string lastName, 
                    string medicalRecord, 
                    string cRID, 
                    string registryID, 
                    string birthDate, 
                    string totalVolume, 
                    string nucleatedCellCount, 
                    string hCT, 
                    string rBCVolume, 
                    string plasmalyte, 
                    string totalNucleatedCells, 
                    string hetastarch, 
                    string preHES_1SedimentationVolume, 
                    string preHES_1SedimentationNC, 
                    string preHES_1SedimentationTNC, 
                    string preHES_1SedimentationHCT, 
                    string preHES_1SedimentationRBC, 
                    string postHES_1SedimentationVolume, 
                    string postHES_1SedimentationNC, 
                    string postHES_1SedimentationTNC, 
                    string postHES_1SedimentationHCT, 
                    string postHES_1SedimentationRBC, 
                    string postHES_1RemovalVolume, 
                    string postHES_1RemovalNC, 
                    string postHES_1RemovalTNC, 
                    string postHES_1RemovalHCT, 
                    string postHES_1RemovalRBC, 
                    string preHES_1SedimentationTNCRecovery, 
                    string postHES_1SedimentationTNCRecovery, 
                    string postHES_1RemovalTNCRecovery, 
                    string productGrossWeight, 
                    string bagTareWeight, 
                    string nucleatedCellCountPP, 
                    string cD34, 
                    string cD3, 
                    string leukapheresisTransferIntoCellBagStartDate, 
                    string leukapheresisTransferIntoCellBagStartTime, 
                    string removeSampleForTesting, 
                    string weightOfBagWithLeukapheresis, 
                    string weightOfEmptyBag, 
                    string a4ReducedNA, 
                    string weightOfLeukapheresisAfterReduction, 
                    string actualDilutionBufferAdded, 
                    string bagWeightAfterAddingDilutionBuffer, 
                    string centrifugeID, 
                    string centrifugationTime, 
                    string centrifugationSpeed, 
                    string targetFinalVolumeIs95G, 
                    string actualAmountOfSupernatantRemoved, 
                    string totalWeightOfBagAfterCompleteDilution, 
                    string cD34ReagentID, 
                    string secondCD34ReagentID, 
                    string incubationStartTime, 
                    string airInjection, 
                    string placedOnRotator, 
                    string rotatorComment, 
                    string incubationStopTime, 
                    string wash1AmountOfBufferTransferredIntoBag, 
                    string wash1CentrifugeID, 
                    string wash1CentrifugationTime, 
                    string wash1CentrifugationSpeed, 
                    string wash1AmountOfSupernatantRemoved, 
                    string wash2AmountOfBufferTransferredIntoBag, 
                    string wash2CentrifugeID, 
                    string wash2CentrifugationTime, 
                    string wash2CentrifugationSpeed, 
                    string wash2AmountOfSupernatantRemoved, 
                    string weightOfBagAfterWashing, 
                    string volumeAdjustmentIsNormal, 
                    string removeProductSampleForAnalysis, 
                    string weightOfCellPreparationBagAfterBufferAddition, 
                    string cliniMACSSeparationDateStarted, 
                    string cliniMACSSeparationTimeStarted, 
                    string cliniMACSSeparationDateEnded, 
                    string cliniMACSSeparationTimeEnded, 
                    string tubingSetReagentID, 
                    string weightOfCellCollectionBagAfterRun, 
                    string weightOfEmptyCellCollectionBag, 
                    string processCode, 
                    string hPCNotApplicable, 
                    string hPCTotalVolume, 
                    string hPCNucleatedCellCount, 
                    string hPCPercentCD34Positive, 
                    string hPCPercentCD3Positive, 
                    string hPCCD34Viability, 
                    string t_CellNotApplicable, 
                    string t_CellAliquotID, 
                    string t_CellTotalVolume, 
                    string t_CellNucleatedCellCount, 
                    string t_CellPercentCD34Positive, 
                    string t_CellPercentCD3Positive, 
                    string pre_SpinNotApplicable, 
                    string pre_SpinTotalVolume, 
                    string pre_SpinNucleatedCellCount, 
                    string pre_SpinPercentCD34Positive, 
                    string pre_SpinPercentCD3Positive, 
                    string post_SpinNotApplicable, 
                    string post_SpinAliquotID, 
                    string post_SpinGrossWeight, 
                    string post_SpinCentrifugeID, 
                    string post_SpinRPMs, 
                    string post_SpinCentrifugeTemperature, 
                    string post_SpinGrossWt, 
                    string post_SpinBagWt, 
                    string post_SpinNucleatedCellCount, 
                    string post_SpinPercentCD34Positive, 
                    string post_SpinPercentCD3Positive, 
                    string post_SpinPercentRecovery, 
                    string hPCBeforePrepTotalVolume, 
                    string hPCBeforePrepNucleatedCellCount, 
                    string hPCBeforePrepPercentCD34Positve, 
                    string hPCBeforePrepPercentCD3Positive, 
                    string hPCBeforePrepCD34Viability, 
                    string hPCAfterPrepTotalVolume, 
                    string hPCAfterPrepNucleatedCellCount, 
                    string hPCAfterPrepPercentCD34Positve, 
                    string hPCAfterPrepPercentCD3Positive, 
                    string hPCAfterPrepCD34Viability, 
                    string cD34PositiveFractionAliquotID, 
                    string cD34PositiveFractionTotalVolume, 
                    string cD34PositiveFractionNucleatedCellCount, 
                    string cD34PositiveFractionPercentCD34Positve, 
                    string cD34PositiveFractionPercentCD3Positive, 
                    string cD34PositiveFractionCD34Viability, 
                    string cD34NegativeFractionTotalVolume, 
                    string cD34NegativeFractionNucleatedCellCount, 
                    string cD34NegativeFractionPercentCD34Positve, 
                    string cD34NegativeFractionPercentCD3Positive, 
                    string cD34NegativeFractionCD34Viability, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "mytag"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Calc", @__tags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given("I navigate to TranstemLab application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.Then("I should be navigated to TranstemLab home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 7
 testRunner.Then("I click on Recipients Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 8
 testRunner.Then("I click on Add Recipient button from Recipient Search Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 9
 testRunner.Then(string.Format("I enter {0} {1} {2} {3} {4} {5} {6} Gender Ethnicity and Client Status in the pag" +
                        "e", recipientID, firstName, lastName, medicalRecord, cRID, registryID, birthDate), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 10
 testRunner.Then("I click on Save button from page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 11
 testRunner.And("I Click on Add a transplant event for patient from RecipientDetail page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.Then("I enter value for all fields in Add Transplant Event page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 13
 testRunner.Then("I click on Save button form Add Tranplant Event Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 14
 testRunner.And("I record recipient information", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.Then("go to home page from Recipient page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 16
 testRunner.And("I start to do a Donor search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.Then("I enter donor information and select that Donor", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 18
 testRunner.And("I start to Add collection", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
 testRunner.Then("I click on Add collection Event link from the Donor Detail page and fill out the " +
                    "required fields", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 20
 testRunner.Then("I click on Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 21
 testRunner.And("I record the system generated donor ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.Then("I Start to Add a Product from Donor home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 23
 testRunner.Then("I click on the Product link to add a new product", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 24
 testRunner.And("I select radio button to enter system generated donor ID and enter the ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.And("I click on the Load Donor ID and check the patient information", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.Then("I click on the sync button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 27
 testRunner.And("I click on the radio button to select donor and press enter key in the keyboard", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.Then("I click on Create Collection Event button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 29
 testRunner.And("I note down the Product ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.And("I click on the Create Product", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.Then("go to home page from Add New Product page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 32
 testRunner.And("I start to do a Recipient search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.And("I enter Recipient Last Name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.Then("I click on Search button on the Recipient Search page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 35
 testRunner.And("I verify the recipient information", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
 testRunner.And("I edit the transplant event to add product", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.Then("go to home page from Recipient page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 38
 testRunner.Then("I click on Product Link and select Batch Processing to Search page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 39
    testRunner.And("I click on Add Batch button to Add Batch page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
    testRunner.And("I select Cell Processing v1 20111 from the drop down list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
    testRunner.And("I click on Search button in the Add Batch page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 42
 testRunner.Then("I select the the Product ID was created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 43
 testRunner.And("I click on the check box of the newly created product", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 44
 testRunner.Then("I select a Technologist from Technologist Name drop down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 45
 testRunner.And("I click on Save button to save the Processing Procedure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
 testRunner.Then("I click on Product List and navigate to Processing page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 47
 testRunner.Then("I click on the Title Arrow", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 48
 testRunner.Then("I navigate to Data Analysis CD34 Selection", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 49
 testRunner.And(string.Format("I fill in HPC Product Aliquot for CD34 Selection (Before Prep/Magnetic Labeling) " +
                        "with {0}, {1}, {2}, {3}, {4}", hPCBeforePrepTotalVolume, hPCBeforePrepNucleatedCellCount, hPCBeforePrepPercentCD34Positve, hPCBeforePrepPercentCD3Positive, hPCBeforePrepCD34Viability), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
 testRunner.And(string.Format("I fill in HPC Product Aliquot for CD34 Selection (After Prep/Magnetic Labeling) w" +
                        "ith {0}, {1}, {2}, {3}, {4}", hPCAfterPrepTotalVolume, hPCAfterPrepNucleatedCellCount, hPCAfterPrepPercentCD34Positve, hPCAfterPrepPercentCD3Positive, hPCAfterPrepCD34Viability), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.And(string.Format("I fill in CD34 Selected Positive Fraction (Cell Collection Bag) with {0}, {1}, {2" +
                        "}, {3}, {4}, {5}", cD34PositiveFractionAliquotID, cD34PositiveFractionTotalVolume, cD34PositiveFractionNucleatedCellCount, cD34PositiveFractionPercentCD34Positve, cD34PositiveFractionPercentCD3Positive, cD34PositiveFractionCD34Viability), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 52
 testRunner.And(string.Format("I fill in CD34 Selected Negative Fraction (Negative Fraction Bag) with {0}, {1}, " +
                        "{2}, {3}, {4}", cD34NegativeFractionTotalVolume, cD34NegativeFractionNucleatedCellCount, cD34NegativeFractionPercentCD34Positve, cD34NegativeFractionPercentCD3Positive, cD34NegativeFractionCD34Viability), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
 testRunner.And("I verify the calculations in Data Analysis CD34 Selection", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
 testRunner.Then("I click LogOutLink", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 55
 testRunner.And("I should be navigated to TranstemLab login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 56
 testRunner.And("I Log Out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
